version: '3'

services:
  my-mongoDB:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: syscoin-bridge
    volumes:
    - db-data:/data/db
    - mongo-config:/data/configdb
    - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
 
volumes:
  db-data:
  mongo-config: